component: worker
replicas: 2
image:
  repository: ghcr.io/giladtrachtenberg/video-demo
  tag: "e9d3d1b1eea6846582255b7fcbb0ecf49a77f071"
migrations:
  enabled: false
commandOverride:
  command: ["celery"]
  args: ["-A", "src.tasks", "worker", "--loglevel=info", "--concurrency=2"]
service:
  enabled: false
configMap:
  enabled: true
  data:
    APP_NAME: video-demo
    DEBUG: "false"
    MINIO_BUCKET: video-demo
    MINIO_SECURE: "false"
sharedSecrets:
  - app-shared-secrets
