component: worker
replicas: 2
image:
  repository: ghcr.io/giladtrachtenberg/video-demo
  tag: "47375e7469a0ccd3d3aed43f4314f621228f4944"
migrations:
  enabled: false
commandOverride:
  command: ["celery"]
  args: ["-A", "src.tasks", "worker", "--loglevel=info", "--concurrency=2"]
service:
  enabled: false
configMap:
  enabled: true
  data:
    APP_NAME: video-demo
    DEBUG: "false"
    MINIO_BUCKET: video-demo
    MINIO_SECURE: "false"
sharedSecrets:
  - app-shared-secrets
